export interface LanguageItem {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGES_LIST: LanguageItem[] = [
  { code: 'ar', name: 'Arabic', nativeName: 'العربية' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', nativeName: '简体中文' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands' },
  { code: 'en-GB', name: 'English (UK)', nativeName: 'English' },
  { code: 'en-US', name: 'English (US)', nativeName: 'English' },
  { code: 'fil', name: 'Filipino', nativeName: 'Filipino' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', nativeName: '한국어' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)', nativeName: 'Português' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)', nativeName: 'Português' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'bn-BD', name: 'Bengali (Bangladesh)', nativeName: 'বাংলা' },
  { code: 'bn-IN', name: 'Bengali (India)', nativeName: 'বাংলা' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'th', name: 'Thai', nativeName: 'ภาษาไทย' },
  { code: 'es-AR', name: 'Spanish (Argentina)', nativeName: 'Español (AR)' },
  { code: 'es-MX', name: 'Spanish (Mexico)', nativeName: 'Español (MX)' },
  { code: 'es-ES', name: 'Spanish (Spain)', nativeName: 'Español (ES)' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
];

const STORAGE_KEY_LANGUAGE = 'funshann_selected_language_v1';

export const getSavedLanguage = (): string => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY_LANGUAGE);
    if (saved && LANGUAGES_LIST.some((l) => l.code === saved)) {
      return saved;
    }
  } catch (e) {
    console.error('Failed to get saved language', e);
  }
  return 'en-US';
};

export const saveSelectedLanguage = (code: string): void => {
  try {
    localStorage.setItem(STORAGE_KEY_LANGUAGE, code);
  } catch (e) {
    console.error('Failed to save selected language', e);
  }
};

// Common translations for key app terminology
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    settings: 'Settings',
    account: 'Account Settings',
    notifications: 'Notifications',
    language: 'Language',
    name: 'Name',
    username: 'Username',
    birthday: 'Birthday',
    mobile: 'Mobile Number',
    email: 'Email',
    password: 'Password',
    twoFactor: 'Two-Factor Authentication',
    theme: 'Theme & Aesthetics',
    privacy: 'Account Privacy',
    permissions: 'Privacy / Permissions',
    media: 'Media & Storage',
    security: 'Security & Login',
    about: 'About Funshann',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    enabled: 'ON',
    disabled: 'OFF',
    home: 'Home',
    explore: 'Explore',
    chat: 'Messages',
    profile: 'Profile',
    following: 'Following',
    followers: 'Followers',
    logout: 'Log Out',
  },
  'es': {
    settings: 'Configuración',
    account: 'Configuración de la cuenta',
    notifications: 'Notificaciones',
    language: 'Idioma',
    name: 'Nombre',
    username: 'Nombre de usuario',
    birthday: 'Cumpleaños',
    mobile: 'Número de móvil',
    email: 'Correo electrónico',
    password: 'Contraseña',
    twoFactor: 'Autenticación en dos pasos',
    theme: 'Tema y estética',
    privacy: 'Privacidad de la cuenta',
    permissions: 'Privacidad / Permisos',
    media: 'Medios y almacenamiento',
    security: 'Seguridad e inicio de sesión',
    about: 'Acerca de Funshann',
    save: 'Guardar',
    cancel: 'Cancelar',
    back: 'Atrás',
    enabled: 'ACTIVADO',
    disabled: 'DESACTIVADO',
    home: 'Inicio',
    explore: 'Explorar',
    chat: 'Mensajes',
    profile: 'Perfil',
    following: 'Siguiendo',
    followers: 'Seguidores',
    logout: 'Cerrar sesión',
  },
  'fr': {
    settings: 'Paramètres',
    account: 'Paramètres du compte',
    notifications: 'Notifications',
    language: 'Langue',
    name: 'Nom',
    username: 'Nom d’utilisateur',
    birthday: 'Date de naissance',
    mobile: 'Numéro de mobile',
    email: 'E-mail',
    password: 'Mot de passe',
    twoFactor: 'Authentification à deux facteurs',
    theme: 'Thème & esthétique',
    privacy: 'Confidentialité du compte',
    permissions: 'Confidentialité / Autorisations',
    media: 'Médias et stockage',
    security: 'Sécurité et connexion',
    about: 'À propos de Funshann',
    save: 'Enregistrer',
    cancel: 'Annuler',
    back: 'Retour',
    enabled: 'ACTIVÉ',
    disabled: 'DÉSACTIVÉ',
    home: 'Accueil',
    explore: 'Explorer',
    chat: 'Messages',
    profile: 'Profil',
    following: 'Abonnements',
    followers: 'Abonnés',
    logout: 'Se déconnecter',
  },
  'de': {
    settings: 'Einstellungen',
    account: 'Kontoeinstellungen',
    notifications: 'Benachrichtigungen',
    language: 'Sprache',
    name: 'Name',
    username: 'Benutzername',
    birthday: 'Geburtstag',
    mobile: 'Mobilnummer',
    email: 'E-Mail',
    password: 'Passwort',
    twoFactor: 'Zwei-Faktor-Authentifizierung',
    theme: 'Design & Ästhetik',
    privacy: 'Konto-Privatsphäre',
    permissions: 'Datenschutz / Berechtigungen',
    media: 'Medien & Speicher',
    security: 'Sicherheit & Anmeldung',
    about: 'Über Funshann',
    save: 'Speichern',
    cancel: 'Abbrechen',
    back: 'Zurück',
    enabled: 'EIN',
    disabled: 'AUS',
    home: 'Start',
    explore: 'Entdecken',
    chat: 'Nachrichten',
    profile: 'Profil',
    following: 'Gefolgt',
    followers: 'Follower',
    logout: 'Abmelden',
  },
  'hi': {
    settings: 'सेटिंग्स',
    account: 'खाता सेटिंग्स',
    notifications: 'सूचनाएं',
    language: 'भाषा',
    name: 'नाम',
    username: 'उपयोगकर्ता नाम',
    birthday: 'जन्मदिन',
    mobile: 'मोबाइल नंबर',
    email: 'ईमेल',
    password: 'पासवर्ड',
    twoFactor: 'दो-चरणीय प्रमाणीकरण',
    theme: 'थीम और दिखावट',
    privacy: 'खाता गोपनीयता',
    permissions: 'गोपनीयता / अनुमतियाँ',
    media: 'मीडिया और संग्रहण',
    security: 'सुरक्षा और लॉगिन',
    about: 'Funshann के बारे में',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    back: 'वापस',
    enabled: 'चालू',
    disabled: 'बंद',
    home: 'होम',
    explore: 'खोजें',
    chat: 'संदेश',
    profile: 'प्रोफ़ाइल',
    following: 'फ़ॉलो कर रहे हैं',
    followers: 'फ़ॉलोअर्स',
    logout: 'लॉग आउट',
  },
  'ar': {
    settings: 'الإعدادات',
    account: 'إعدادات الحساب',
    notifications: 'الإشعارات',
    language: 'اللغة',
    name: 'الاسم',
    username: 'اسم المستخدم',
    birthday: 'تاريخ الميلاد',
    mobile: 'رقم الهاتف المحمول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    twoFactor: 'المصادقة الثنائية',
    theme: 'المظهر والتصميم',
    privacy: 'خصوصية الحساب',
    permissions: 'الخصوصية / الأذونات',
    media: 'الوسائط والتخزين',
    security: 'الأمان وتسجيل الدخول',
    about: 'حول Funshann',
    save: 'حفظ',
    cancel: 'إلغاء',
    back: 'رجوع',
    enabled: 'مفعل',
    disabled: 'معطل',
    home: 'الرئيسية',
    explore: 'استكشاف',
    chat: 'الرسائل',
    profile: 'الملف الشخصي',
    following: 'أتابعهم',
    followers: 'المتابعون',
    logout: 'تسجيل الخروج',
  },
  'zh-CN': {
    settings: '设置',
    account: '账户设置',
    notifications: '通知',
    language: '语言',
    name: '姓名',
    username: '用户名',
    birthday: '生日',
    mobile: '手机号码',
    email: '电子邮件',
    password: '密码',
    twoFactor: '双重身份验证',
    theme: '主题与外观',
    privacy: '账户隐私',
    permissions: '隐私 / 权限',
    media: '媒体与存储',
    security: '安全与登录',
    about: '关于 Funshann',
    save: '保存',
    cancel: '取消',
    back: '返回',
    enabled: '开启',
    disabled: '关闭',
    home: '首页',
    explore: '发现',
    chat: '消息',
    profile: '个人资料',
    following: '关注中',
    followers: '粉丝',
    logout: '退出登录',
  },
  'ja': {
    settings: '設定',
    account: 'アカウント設定',
    notifications: '通知',
    language: '言語',
    name: '名前',
    username: 'ユーザー名',
    birthday: '誕生日',
    mobile: '携帯電話番号',
    email: 'メールアドレス',
    password: 'パスワード',
    twoFactor: '二要素認証',
    theme: 'テーマとデザイン',
    privacy: 'アカウントのプライバシー',
    permissions: 'プライバシーと権限',
    media: 'メディアとストレージ',
    security: 'セキュリティとログイン',
    about: 'Funshannについて',
    save: '保存',
    cancel: 'キャンセル',
    back: '戻る',
    enabled: 'オン',
    disabled: 'オフ',
    home: 'ホーム',
    explore: '見つける',
    chat: 'メッセージ',
    profile: 'プロフィール',
    following: 'フォロー中',
    followers: 'フォロワー',
    logout: 'ログアウト',
  },
};

export const getTranslation = (langCode: string, key: string): string => {
  const normalizedCode = TRANSLATIONS[langCode]
    ? langCode
    : langCode.startsWith('es')
    ? 'es'
    : 'en-US';
  return TRANSLATIONS[normalizedCode]?.[key] || TRANSLATIONS['en-US']?.[key] || key;
};
